// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/ogataka50/ent-test/ent/runtime.go

const (
	Version = "v0.6.1-0.20210226201854-109228f0a30b"            // Version of ent codegen.
	Sum     = "h1:jX3+rMLZLhhAWF9IgEurjxnjoHz5nT1SQoFzqZzD+uA=" // Sum of ent codegen.
)
