// Code generated by entc, DO NOT EDIT.

package itemgroup

const (
	// Label holds the string label denoting the itemgroup type in the database.
	Label = "item_group"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeGroupItem holds the string denoting the group_item edge name in mutations.
	EdgeGroupItem = "group_item"

	// Table holds the table name of the itemgroup in the database.
	Table = "item_groups"
	// GroupItemTable is the table the holds the group_item relation/edge. The primary key declared below.
	GroupItemTable = "item_item_group"
	// GroupItemInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	GroupItemInverseTable = "items"
)

// Columns holds all SQL columns for itemgroup fields.
var Columns = []string{
	FieldID,
	FieldName,
}

var (
	// GroupItemPrimaryKey and GroupItemColumn2 are the table columns denoting the
	// primary key for the group_item relation (M2M).
	GroupItemPrimaryKey = []string{"item_id", "item_group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
