// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogataka50/ent-test/ent/itemvariation"
	"github.com/ogataka50/ent-test/ent/predicate"
)

// ItemVariationDelete is the builder for deleting a ItemVariation entity.
type ItemVariationDelete struct {
	config
	hooks    []Hook
	mutation *ItemVariationMutation
}

// Where adds a new predicate to the ItemVariationDelete builder.
func (ivd *ItemVariationDelete) Where(ps ...predicate.ItemVariation) *ItemVariationDelete {
	ivd.mutation.predicates = append(ivd.mutation.predicates, ps...)
	return ivd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ivd *ItemVariationDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ivd.hooks) == 0 {
		affected, err = ivd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ItemVariationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ivd.mutation = mutation
			affected, err = ivd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ivd.hooks) - 1; i >= 0; i-- {
			mut = ivd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ivd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ivd *ItemVariationDelete) ExecX(ctx context.Context) int {
	n, err := ivd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ivd *ItemVariationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: itemvariation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: itemvariation.FieldID,
			},
		},
	}
	if ps := ivd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ivd.driver, _spec)
}

// ItemVariationDeleteOne is the builder for deleting a single ItemVariation entity.
type ItemVariationDeleteOne struct {
	ivd *ItemVariationDelete
}

// Exec executes the deletion query.
func (ivdo *ItemVariationDeleteOne) Exec(ctx context.Context) error {
	n, err := ivdo.ivd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itemvariation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ivdo *ItemVariationDeleteOne) ExecX(ctx context.Context) {
	ivdo.ivd.ExecX(ctx)
}
