// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/ogataka50/ent-test/ent/itemgroup"
)

// ItemGroup is the model entity for the ItemGroup schema.
type ItemGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemGroupQuery when eager-loading is set.
	Edges ItemGroupEdges `json:"edges"`
}

// ItemGroupEdges holds the relations/edges for other nodes in the graph.
type ItemGroupEdges struct {
	// GroupItem holds the value of the group_item edge.
	GroupItem []*Item `json:"group_item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GroupItemOrErr returns the GroupItem value or an error if the edge
// was not loaded in eager-loading.
func (e ItemGroupEdges) GroupItemOrErr() ([]*Item, error) {
	if e.loadedTypes[0] {
		return e.GroupItem, nil
	}
	return nil, &NotLoadedError{edge: "group_item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ItemGroup) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case itemgroup.FieldID:
			values[i] = &sql.NullInt64{}
		case itemgroup.FieldName:
			values[i] = &sql.NullString{}
		default:
			return nil, fmt.Errorf("unexpected column %q for type ItemGroup", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ItemGroup fields.
func (ig *ItemGroup) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case itemgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ig.ID = int(value.Int64)
		case itemgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ig.Name = value.String
			}
		}
	}
	return nil
}

// QueryGroupItem queries the "group_item" edge of the ItemGroup entity.
func (ig *ItemGroup) QueryGroupItem() *ItemQuery {
	return (&ItemGroupClient{config: ig.config}).QueryGroupItem(ig)
}

// Update returns a builder for updating this ItemGroup.
// Note that you need to call ItemGroup.Unwrap() before calling this method if this ItemGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (ig *ItemGroup) Update() *ItemGroupUpdateOne {
	return (&ItemGroupClient{config: ig.config}).UpdateOne(ig)
}

// Unwrap unwraps the ItemGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ig *ItemGroup) Unwrap() *ItemGroup {
	tx, ok := ig.config.driver.(*txDriver)
	if !ok {
		panic("ent: ItemGroup is not a transactional entity")
	}
	ig.config.driver = tx.drv
	return ig
}

// String implements the fmt.Stringer.
func (ig *ItemGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ItemGroup(")
	builder.WriteString(fmt.Sprintf("id=%v", ig.ID))
	builder.WriteString(", name=")
	builder.WriteString(ig.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ItemGroups is a parsable slice of ItemGroup.
type ItemGroups []*ItemGroup

func (ig ItemGroups) config(cfg config) {
	for _i := range ig {
		ig[_i].config = cfg
	}
}
