// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogataka50/ent-test/ent/itemgroup"
	"github.com/ogataka50/ent-test/ent/predicate"
)

// ItemGroupDelete is the builder for deleting a ItemGroup entity.
type ItemGroupDelete struct {
	config
	hooks    []Hook
	mutation *ItemGroupMutation
}

// Where adds a new predicate to the ItemGroupDelete builder.
func (igd *ItemGroupDelete) Where(ps ...predicate.ItemGroup) *ItemGroupDelete {
	igd.mutation.predicates = append(igd.mutation.predicates, ps...)
	return igd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (igd *ItemGroupDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(igd.hooks) == 0 {
		affected, err = igd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ItemGroupMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			igd.mutation = mutation
			affected, err = igd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(igd.hooks) - 1; i >= 0; i-- {
			mut = igd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, igd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (igd *ItemGroupDelete) ExecX(ctx context.Context) int {
	n, err := igd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (igd *ItemGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: itemgroup.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: itemgroup.FieldID,
			},
		},
	}
	if ps := igd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, igd.driver, _spec)
}

// ItemGroupDeleteOne is the builder for deleting a single ItemGroup entity.
type ItemGroupDeleteOne struct {
	igd *ItemGroupDelete
}

// Exec executes the deletion query.
func (igdo *ItemGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := igdo.igd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{itemgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (igdo *ItemGroupDeleteOne) ExecX(ctx context.Context) {
	igdo.igd.ExecX(ctx)
}
