// Code generated by entc, DO NOT EDIT.

package itemvariation

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ogataka50/ent-test/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// VariantName applies equality check predicate on the "variant_name" field. It's identical to VariantNameEQ.
func VariantName(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVariantName), v))
	})
}

// VariantNameEQ applies the EQ predicate on the "variant_name" field.
func VariantNameEQ(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldVariantName), v))
	})
}

// VariantNameNEQ applies the NEQ predicate on the "variant_name" field.
func VariantNameNEQ(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldVariantName), v))
	})
}

// VariantNameIn applies the In predicate on the "variant_name" field.
func VariantNameIn(vs ...string) predicate.ItemVariation {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ItemVariation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldVariantName), v...))
	})
}

// VariantNameNotIn applies the NotIn predicate on the "variant_name" field.
func VariantNameNotIn(vs ...string) predicate.ItemVariation {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ItemVariation(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldVariantName), v...))
	})
}

// VariantNameGT applies the GT predicate on the "variant_name" field.
func VariantNameGT(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldVariantName), v))
	})
}

// VariantNameGTE applies the GTE predicate on the "variant_name" field.
func VariantNameGTE(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldVariantName), v))
	})
}

// VariantNameLT applies the LT predicate on the "variant_name" field.
func VariantNameLT(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldVariantName), v))
	})
}

// VariantNameLTE applies the LTE predicate on the "variant_name" field.
func VariantNameLTE(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldVariantName), v))
	})
}

// VariantNameContains applies the Contains predicate on the "variant_name" field.
func VariantNameContains(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldVariantName), v))
	})
}

// VariantNameHasPrefix applies the HasPrefix predicate on the "variant_name" field.
func VariantNameHasPrefix(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldVariantName), v))
	})
}

// VariantNameHasSuffix applies the HasSuffix predicate on the "variant_name" field.
func VariantNameHasSuffix(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldVariantName), v))
	})
}

// VariantNameEqualFold applies the EqualFold predicate on the "variant_name" field.
func VariantNameEqualFold(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldVariantName), v))
	})
}

// VariantNameContainsFold applies the ContainsFold predicate on the "variant_name" field.
func VariantNameContainsFold(v string) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldVariantName), v))
	})
}

// HasOriginItem applies the HasEdge predicate on the "origin_item" edge.
func HasOriginItem() predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OriginItemTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OriginItemTable, OriginItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOriginItemWith applies the HasEdge predicate on the "origin_item" edge with a given conditions (other predicates).
func HasOriginItemWith(preds ...predicate.Item) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OriginItemInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OriginItemTable, OriginItemColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ItemVariation) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ItemVariation) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ItemVariation) predicate.ItemVariation {
	return predicate.ItemVariation(func(s *sql.Selector) {
		p(s.Not())
	})
}
