// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// ItemDescription is the predicate function for itemdescription builders.
type ItemDescription func(*sql.Selector)

// ItemGroup is the predicate function for itemgroup builders.
type ItemGroup func(*sql.Selector)

// ItemVariation is the predicate function for itemvariation builders.
type ItemVariation func(*sql.Selector)
